import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const FAQ = () => {
  const faqs = [
    {
      category: "Getting Started",
      questions: [
        {
          q: "What is Abun?",
          a: "Abun is an all-in-one AI-powered SEO and content marketing toolkit that helps marketers, founders, and SEO experts drive traffic, generate leads, and achieve business growth through automated content creation and optimization."
        },
        {
          q: "How do I get started?",
          a: "Simply sign up for a free account, choose your plan, and you can start creating AI-powered content immediately. No credit card required for the trial period."
        },
        {
          q: "Do I need technical knowledge to use Abun?",
          a: "Not at all! Abun is designed to be user-friendly. Our AI handles the technical aspects while you focus on your content strategy."
        }
      ]
    },
    {
      category: "Features & Tools",
      questions: [
        {
          q: "What types of content can Abun create?",
          a: "Abun can create blog articles, SEO-optimized content, glossaries, comparison pages, infographics, stats pages, and even convert videos to articles. All content is human-like and optimized for search engines."
        },
        {
          q: "How does AI Blog Automation work?",
          a: "Our AI Blog Automation can plan and create content for months in advance. Simply set your topics and schedule, and Abun will automatically generate and optimize articles based on your preferences."
        },
        {
          q: "Can I use Abun for multiple websites?",
          a: "Yes! Depending on your plan, you can manage multiple websites. Professional plans include up to 5 websites, while Enterprise plans offer unlimited websites."
        },
        {
          q: "Does Abun integrate with my CMS?",
          a: "Yes! Abun integrates with WordPress, Shopify, Wix, Webflow, and connects with Google Search Console for performance tracking."
        }
      ]
    },
    {
      category: "SEO & Keywords",
      questions: [
        {
          q: "How does keyword research work?",
          a: "Abun offers multiple keyword research tools including AI-powered keyword discovery, long-tail keyword generation, competitor keyword analysis, and ICP-to-keyword research to find exactly what your target audience is searching for."
        },
        {
          q: "Can I steal my competitors' keywords?",
          a: "Yes! Our competitor analysis tool identifies which keywords your competitors are ranking for, allowing you to target the same terms and gain competitive advantage."
        },
        {
          q: "Does Abun help with technical SEO?",
          a: "Absolutely! Abun automatically adds JSON schema markup, handles fast indexing, builds internal links, and provides AI-powered technical SEO recommendations."
        }
      ]
    },
    {
      category: "Billing & Plans",
      questions: [
        {
          q: "Is there a free trial?",
          a: "Yes! We offer a 14-day free trial for all plans. No credit card required to start."
        },
        {
          q: "Can I cancel anytime?",
          a: "Yes, you can cancel your subscription at any time. No long-term contracts or cancellation fees."
        },
        {
          q: "What happens if I exceed my article limit?",
          a: "You can either upgrade to a higher plan or purchase additional articles as needed. We'll notify you before you reach your limit."
        },
        {
          q: "Do you offer refunds?",
          a: "Yes, we offer a 30-day money-back guarantee if you're not satisfied with our service."
        }
      ]
    },
    {
      category: "Support & Security",
      questions: [
        {
          q: "What kind of support do you offer?",
          a: "All plans include email support. Professional plans get priority support, and Enterprise plans receive 24/7 dedicated support with a personal account manager."
        },
        {
          q: "Is my data secure?",
          a: "Yes! We use industry-standard encryption and security measures to protect your data. We're also GDPR compliant."
        },
        {
          q: "Who owns the content created by Abun?",
          a: "You do! All content generated by Abun is 100% yours to use however you like."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-4xl">
          {/* Header */}
          <div className="text-center mb-16 fade-in">
            <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold mb-6">
              Frequently Asked <span className="text-gradient">Questions</span>
            </h1>
            <p className="text-lg sm:text-xl text-muted-foreground">
              Everything you need to know about Abun and how it can help grow your business
            </p>
          </div>

          {/* FAQ Sections */}
          <div className="space-y-12">
            {faqs.map((section, sectionIndex) => (
              <div key={sectionIndex} className="fade-in" style={{ animationDelay: `${sectionIndex * 0.1}s` }}>
                <h2 className="text-2xl font-bold mb-6">{section.category}</h2>
                <Accordion type="single" collapsible className="space-y-4">
                  {section.questions.map((faq, faqIndex) => (
                    <AccordionItem 
                      key={faqIndex} 
                      value={`${sectionIndex}-${faqIndex}`}
                      className="border border-border/50 rounded-lg px-6 bg-card/50"
                    >
                      <AccordionTrigger className="text-left hover:no-underline">
                        <span className="font-semibold">{faq.q}</span>
                      </AccordionTrigger>
                      <AccordionContent className="text-muted-foreground pt-2">
                        {faq.a}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            ))}
          </div>

          {/* CTA Section */}
          <div className="mt-16 text-center p-8 bg-accent/30 rounded-lg border border-border/50">
            <h3 className="text-2xl font-bold mb-4">Still have questions?</h3>
            <p className="text-muted-foreground mb-6">
              Our support team is here to help you succeed
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="mailto:support@abun.com" 
                className="px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors font-semibold"
              >
                Contact Support
              </a>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default FAQ;
